# frontend/Dockerfile.prod

# Tomamos artefactos desde la imagen build ya generada
FROM frontend-app:build AS build

# Imagen final ligera
FROM nginx:alpine

# (Opcional) Config simple para SPA (React Router)
# Si NO usas React Router, puedes omitir esto.
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar build estático a Nginx
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

# Nginx ya trae el CMD por defecto