# Usamos una imagen que ya tenga Java y JMeter instalado
FROM justb4/jmeter:5.5


WORKDIR /tests

# Copiamos los scripts de carga
COPY plans/ /tests/plans/

# Script to run a specific plan or run them sequentially
RUN echo '#!/bin/sh' > /run_tests.sh && \
    echo 'if [ -z "$1" ]; then' >> /run_tests.sh && \
    echo '  echo "Ejecutando todos los scripts secuencialmente..."' >> /run_tests.sh && \
    echo '  for jmx in /tests/plans/*.jmx; do' >> /run_tests.sh && \
    echo '    echo "Ejecutando: $jmx"' >> /run_tests.sh && \
    echo '    filename=$(basename -- "$jmx")' >> /run_tests.sh && \
    echo '    basename="${filename%.*}"' >> /run_tests.sh && \
    echo '    jmeter -n -t "$jmx" -l /app/results/${basename}_results.csv -e -o /app/results/${basename}_html_report' >> /run_tests.sh && \
    echo '  done' >> /run_tests.sh && \
    echo 'else' >> /run_tests.sh && \
    echo '  echo "Ejecutando: $1"' >> /run_tests.sh && \
    echo '  filename=$(basename -- "$1")' >> /run_tests.sh && \
    echo '  basename="${filename%.*}"' >> /run_tests.sh && \
    echo '  jmeter -n -t "/tests/plans/$1" -l /app/results/${basename}_results.csv -e -o /app/results/${basename}_html_report' >> /run_tests.sh && \
    echo 'fi' >> /run_tests.sh && \
    chmod +x /run_tests.sh

ENTRYPOINT ["/run_tests.sh"]
