# Imagen base ligera sugerida por el laboratorio 
FROM postman/newman:6-alpine

# Directorio de trabajo para las colecciones
WORKDIR /etc/newman

# Copiamos los archivos de la colección y ambiente
COPY . .

# Definimos el entrypoint para ejecutar newman directamente
ENTRYPOINT ["newman"]